- alias: Away
  trigger:
    platform: state
    entity_id: device_tracker.android890623178d4bcedd
    state: 'not_home'
  action:
    - service: light.turn_off
    - service: climate.set_away_mode
      data:
        entity_id: climate.hallway
        away_mode: true
- alias: Home
  trigger:
    platform: state
    entity_id: device_tracker.android890623178d4bcedd
    state: 'home'
  action:
    - service: homeassistant.turn_on
      entity_id: group.living_room
    - service: climate.set_away_mode
      data:
        entity_id: climate.hallway
        away_mode: false
- alias: Netflix - Play
  trigger:
    platform: state
    entity_id: media_player.toms
    state: 'playing'
  action:
    service: light.turn_off
    entity_id: light.couch_2
- alias: Netflix - Pause
  trigger:
    - platform: state
      entity_id: media_player.toms
      state: 'paused'
    - platform: state
      entity_id: media_player.toms
      state: 'idle'
    - platform: state
      entity_id: media_player.toms
      state: 'off'
  action:
    service: light.turn_on
    entity_id: light.couch_2
- alias: Alarm
  trigger:
    platform: time
    after: "07:40:00"
  condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: group.people
    state: home
  action:
    service: light.turn_on
    entity_id: group.bedroom
    data:
      transition: 1200
      brightness: 254
      color_temp: 230
- alias: Bathroom Motion On
  trigger:
    - platform: state
      entity_id: sensor.bathroom_motion_alarm_level_2_1
      to: '255'
  condition:
    - condition: state
      entity_id: group.lights
      state: 'on'
  action:
    service: light.turn_on
    entity_id: group.bathroom
- alias: Bathroom Motion Off
  trigger:
    - platform: state
      entity_id: sensor.bathroom_motion_alarm_level_2_1
      to: '0'
  action:
    service: light.turn_off
    entity_id: group.bathroom
