- alias: Transition Away
  trigger:
    platform: state
    entity_id: group.people
    to: 'not_home'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.presence
      option: away
- alias: Transition Home
  trigger:
    platform: state
    entity_id: group.people
    to: 'home'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.presence
      option: home

- alias: Away
  trigger:
    platform: state
    entity_id: input_select.presence
    to: away
  action:
    - service: homeassistant.turn_off
      entity_id: group.lights
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.display_state
    - service: climate.set_away_mode
      data:
        entity_id: climate.hallway
        away_mode: true
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.ha_alarm
    - service: input_select.select_option
      data:
        entity_id: input_select.motion_lights
        option: 'off'
- alias: Home
  trigger:
    platform: state
    entity_id: input_select.presence
    to: home
  action:
    - service: homeassistant.turn_on
      entity_id: group.living_room
    - service: climate.set_away_mode
      data:
        entity_id: climate.hallway
        away_mode: false
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.ha_alarm
    - service: input_select.select_option
      data:
        entity_id: input_select.motion_lights
        option: 'on'

- alias: Netflix - Play
  trigger:
    platform: state
    entity_id: media_player.toms
    to: 'playing'
  action:
    service: light.turn_off
    entity_id: light.couch_2
- alias: Netflix - Pause
  trigger:
    - platform: state
      entity_id: media_player.toms
      to: 'paused'
    - platform: state
      entity_id: media_player.toms
      to: 'idle'
    - platform: state
      entity_id: media_player.toms
      to: 'off'
  action:
    service: light.turn_on
    entity_id: light.couch_2

- alias: Wakeup (and run)
  initial_state: false
  trigger:
    platform: time
    at: '07:20:00'
  condition:
  - condition: time
    weekday:
      - tue
      - thu
  - condition: state
    entity_id: input_select.presence
    state: home
  - condition: state
    entity_id: input_select.house_mode
    state: sleeping
  - condition: numeric_state
    entity_id: sensor.dark_sky_precip_probability
    below: 10
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.house_mode
        option: awake
    - delay: '00:00:05'
    - service: homeassistant.turn_off
      entity_id: switch.fluxer
    - service: light.turn_on
      entity_id: group.bedroom
      data:
        transition: 1200
        brightness: 254
        color_temp: 230
    - delay: '00:20:00'
    - service: homeassistant.turn_on
      entity_id: switch.fluxer

- alias: Intruder
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001535b7c
      to: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00012dae15
      to: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00010673c9
      to: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.ha_alarm

- alias: Crypto Miner Low Hash Rate
  trigger:
    - platform: numeric_state
      entity_id: sensor.eth_rate
      below: 32
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
      for:
        hours: 1
  action:
    service: notify.html5
    data:
      message: 'Crypto miner hash rate is < 32, and house is currently set to away'
      title: 'Low hash rate'

- alias: Alarm triggered notification
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: 'triggered'
  action:
    service: notify.html5
    data:
      message: 'Alarm triggered'
      title: 'Alarm'

- alias: Toggle House Mode
  trigger:
    platform: state
    entity_id: binary_sensor.switch_158d00013f9a76
    to: 'on'
  action:
    service: input_select.select_next
    data:
      entity_id: input_select.house_mode

- alias: Sleeping
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: sleeping
  action:
    - service: homeassistant.turn_off
      entity_id: group.lights
    - service: homeassistant.turn_off
      entity_id: switch.fluxer
    - service: input_select.select_option
      data:
        entity_id: input_select.motion_lights
        option: 'night'
- alias: Awake
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: awake
  action:
    - service: homeassistant.turn_on
      entity_id: group.living_room
    - service: homeassistant.turn_on
      entity_id: switch.fluxer
    - service: input_select.select_option
      data:
        entity_id: input_select.motion_lights
        option: 'on'

- alias: Display State Change
  trigger:
    platform: state
    entity_id: input_boolean.display_state
  action:
    service: shell_command.enable_display

# - alias: Chromecast Turn TV On
#   trigger:
#     platform: state
#     entity_id: media_player.toms
#     from: 'off'
#   condition:
#   - condition: state
#     entity_id: switch.tv_power
#     state: 'off'
#   action:
#     - service: homeassistant.turn_on
#       entity_id: switch.tv_power
# 
# - alias: Chromecast Turn TV Off Delayed
#   trigger:
#     platform: state
#     entity_id: media_player.toms
#     to: 'off'
#   condition:
#   - condition: state
#     entity_id: switch.tv_power
#     state: 'on'
#   action:
#     - service: homeassistant.turn_on
#       entity_id: switch.tv_power

- alias: Crypto Price Alerts Bitcoin
  trigger:
    - platform: numeric_state
      entity_id: sensor.bitcoin
      above: 20000
  action:
    - service: notify.html5
      data:
        message: 'Bitcoin is above $20k!'
        title: 'Bitcoin Price'
    - service: light.turn_on
      entity_id: light.gateway_light_f0b429cbf3e0
      data:
        rgb_color: [0, 255, 0]

- alias: Crypto Price Alerts Ethereum
  trigger:
    - platform: numeric_state
      entity_id: sensor.ethereum
      above: 2000
  action:
    - service: notify.html5
      data:
        message: 'Ethereum is above $2000!'
        title: 'Ethereum Price'
    - service: light.turn_on
      entity_id: light.gateway_light_f0b429cbf3e0
      data:
        rgb_color: [0, 255, 0]
