- alias: Transition Away
  trigger:
    platform: state
    entity_id: group.people
    state: 'not_home'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.presence
      option: away
- alias: Transition Home
  trigger:
    platform: state
    entity_id: group.people
    state: 'home'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.presence
      option: home

- alias: Away
  trigger:
    platform: state
    entity_id: input_select.presence
    to: away
  action:
    - service: homeassistant.turn_off
      entity_id: group.lights
    - service: climate.set_away_mode
      data:
        entity_id: climate.hallway
        away_mode: true
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.ha_alarm
- alias: Home
  trigger:
    platform: state
    entity_id: input_select.presence
    to: home
  action:
    - service: homeassistant.turn_on
      entity_id: group.living_room
    - service: climate.set_away_mode
      data:
        entity_id: climate.hallway
        away_mode: false
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.ha_alarm

- alias: Netflix - Play
  trigger:
    platform: state
    entity_id: media_player.toms
    state: 'playing'
  action:
    service: light.turn_off
    entity_id: light.couch_2
- alias: Netflix - Pause
  trigger:
    - platform: state
      entity_id: media_player.toms
      state: 'paused'
    - platform: state
      entity_id: media_player.toms
      state: 'idle'
    - platform: state
      entity_id: media_player.toms
      state: 'off'
  action:
    service: light.turn_on
    entity_id: light.couch_2

- alias: Wakeup
  trigger:
    platform: time
    after: '07:40:00'
  condition:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  - condition: state
    entity_id: input_select.presence
    state: home
  - condition: state
    entity_id: input_select.house_mode
    state: sleeping
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.house_mode
        option: awake
    - delay: '00:00:05'
    - service: homeassistant.turn_off
      entity_id: switch.fluxer
    - service: light.turn_on
      entity_id: group.bedroom
      data:
        transition: 1200
        brightness: 254
        color_temp: 230
    - delay: '00:20:00'
    - service: homeassistant.turn_on
      entity_id: switch.fluxer

- alias: Bathroom Motion On Awake
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00012dae15
  condition:
    - condition: state
      entity_id: input_select.house_mode
      state: awake
  action:
    service: homeassistant.turn_on
    entity_id: script.bathroom_timer_on_awake
- alias: Bathroom Motion On Sleeping
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00012dae15
      to: 'on'
  condition:
    - condition: state
      entity_id: input_select.house_mode
      state: sleeping
  action:
    service: homeassistant.turn_on
    entity_id: script.bathroom_timer_on_sleeping

- alias: Bedroom Motion On
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001535b7c
      to: 'on'
  condition:
    - condition: state
      entity_id: input_select.house_mode
      state: awake
    - condition: time
      before: '07:40:00'
      after: '08:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: script.bedroom_timer_on

- alias: Intruder
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001535b7c
      state: 'on'
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d00012dae15
      state: 'on'
    - platform: state
      entity_id: binary_sensor.door_window_sensor_158d00010673c9
      state: 'on'
  condition:
    - condition: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_away
  action:
    service: alarm_control_panel.alarm_trigger
    entity_id: alarm_control_panel.ha_alarm

- alias: Alarm triggered notification
  trigger:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      to: 'triggered'
  action:
    service: notify.html5
    data:
      message: 'Alarm triggered'
      title: 'Alarm'
# - alias: Alarm armed notification
#   trigger:
#     platform: state
#     entity_id: alarm_control_panel.ha_alarm
#     to: 'armed_away'
#   action:
#     service: notify.html5
#     data:
#       message: 'Alarm armed'
#       title: 'Alarm'

- alias: Toggle House Mode
  trigger:
    platform: state
    entity_id: binary_sensor.switch_158d00013f9a76
    to: 'on'
  action:
    service: input_select.select_next
    data:
      entity_id: input_select.house_mode

- alias: Sleeping
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: sleeping
  action:
    - service: homeassistant.turn_off
      entity_id: group.lights
    - service: homeassistant.turn_off
      entity_id: switch.fluxer
- alias: Awake
  trigger:
    platform: state
    entity_id: input_select.house_mode
    to: awake
  action:
    - service: homeassistant.turn_on
      entity_id: group.living_room
    - service: homeassistant.turn_on
      entity_id: switch.fluxer
