# NOTE: This is currently managed directly in the home-assistant ui. This is
# now a backup of that config
resources:
  - type: js
    url: /local/plan-coordinates.js?v=1
title: Home
views:
  - cards:
      - entity: weather.dark_sky
        type: weather-forecast
      - entities:
          - input_select.house_mode
          - input_select.presence
          - input_select.motion_lights
          - input_select.activity
        title: States
        type: glance
      - entity: climate.hallway
        type: thermostat
      - entities:
          - entity: light.bedroom
            tap_action:
              action: toggle
          - entity: light.bathroom
            tap_action:
              action: toggle
          - entity: light.living_room
            tap_action:
              action: toggle
          - entity: switch.fluxer
            tap_action:
              action: toggle
        show_state: false
        title: Light Control
        type: glance
      - entities:
          - entity: script.tv_power
            icon: 'mdi:power'
            name: TV Power
            tap_action: toggle
          - entity: script.tv_volume_up
            icon: 'mdi:chevron-up'
            name: Up
            tap_action: toggle
          - entity: script.tv_volume_down
            icon: 'mdi:chevron-down'
            name: Down
            tap_action: toggle
          - entity: media_player.gpm_desktop_player
            service: media_player.media_play_pause
            tap_action: call-service
        show_state: false
        title: Media Control
        type: glance
      - elements:
          - entity: light.bedroom
            style:
              left: 61%
              top: 24%
            tap_action: toggle
            type: state-icon
          - entity: light.bathroom
            style:
              left: 24%
              top: 31%
            tap_action: toggle
            type: state-icon
          - entity: sensor.hallway_thermostat_temperature
            style:
              left: 40%
              top: 47%
            type: state-label
          - entity: sensor.hallway_thermostat_humidity
            style:
              left: 40%
              top: 50%
            type: state-label
          - entity: light.couch_1
            style:
              left: 50%
              top: 43%
            tap_action: toggle
            type: state-icon
          - entity: light.couch_2
            style:
              left: 75%
              top: 43%
            tap_action: toggle
            type: state-icon
          - entity: light.desk
            style:
              left: 77%
              top: 75%
            tap_action: toggle
            type: state-icon
          - entity: light.dining_room
            style:
              left: 47%
              top: 95%
            tap_action: toggle
            type: state-icon
          - entity: sensor.temperature_158d00011003cd
            style:
              left: 6%
              top: 32%
            type: state-label
          - entity: sensor.humidity_158d00011003cd
            style:
              left: 6%
              top: 35%
            type: state-label
          - entity: sensor.temperature_158d0002b56e08
            style:
              left: 74%
              top: 65%
            type: state-label
          - entity: sensor.humidity_158d0002b56e08
            style:
              left: 74%
              top: 68.5%
            type: state-label
          - entity: binary_sensor.door_window_sensor_158d00010673c9
            style:
              left: 27%
              top: 92%
            type: state-icon
          - icon: 'mdi:power'
            service: script.tv_power
            style:
              left: 70%
              top: 75%
            tap_action: call-service
            type: icon
          - entity: binary_sensor.motion_sensor_158d00012dae15
            style:
              left: 25%
              top: 23%
            type: state-icon
          - entity: binary_sensor.motion_sensor_158d0001535b7c
            style:
              left: 75%
              top: 33%
            type: state-icon
          - entity: sensor.temperature_158d000159f9f2
            style:
              left: 90%
              top: 43%
            type: state-label
          - entity: sensor.humidity_158d000159f9f2
            style:
              left: 90%
              top: 46%
            type: state-label
          - entity: media_player.living_room_home
            style:
              left: 24.5%
              top: 67.5%
            type: state-icon
        image: /local/apt_floorplan.png
        type: picture-elements
    id: main
    title: Main
  - cards:
      - entities:
          - entity: script.tv_power
            icon: 'mdi:power'
            name: Power
            tap_action: toggle
          - entity: script.tv_volume_up
            icon: 'mdi:chevron-up'
            name: Up
            tap_action: toggle
          - entity: script.tv_volume_down
            icon: 'mdi:chevron-down'
            name: Down
            tap_action: toggle
        show_name: false
        show_state: false
        title: TV
        type: glance
      - entity: media_player.gpm_desktop_player
        type: media-control
    id: media
    title: Media
  - cards:
      - type: thermostat
        entity: climate.hallway
      - type: entities
        entities:
          - entity: sensor.temperature_158d00011003cd
          - entity: sensor.hallway_thermostat_humidity
          - entity: sensor.humidity_158d00011003cd
        show_header_toggle: false
        title: Temperatures
      - camera_image: camera.home
        entity: camera.home
        show_info: true
        tap_action: dialog
        title: home
        type: picture-entity
      - camera_image: camera.radar
        entity: camera.radar
        show_info: true
        tap_action: dialog
        title: radar
        type: picture-entity
      - type: history-graph
        entities:
          - sensor.temperature_158d000159f9f2
          - sensor.temperature_158d00011003cd
    id: climate
    title: Climate
  - cards:
      - entities:
          - light.couch_1
          - light.couch_2
          - light.hanging_light_1
          - light.hanging_light_2
          - light.hanging_light_3
          - light.desk_lamp_top
          - light.desk_lamp_bottom
        show_header_toggle: true
        title: Living Room
        type: entities
      - entities:
          - light.bedroom_1
          - light.bedroom_2
          - light.bedroom_3
        show_header_toggle: true
        title: Bedroom
        type: entities
      - entities:
          - light.bathroom_1
          - light.bathroom_2
          - light.bathroom_3
          - light.bathroom_4
        show_header_toggle: true
        title: Bathroom
        type: entities
    title: Lights
  - cards:
      - entities:
          - automation.wakeup_and_run
          - automation.away
          - automation.transition_home
          - automation.crypto_price_alerts_ethereum
          - automation.sleeping
          - automation.netflix__play
          - automation.transition_away
          - automation.activity__tv
          - automation.awake
          - automation.intruder
          - automation.home
          - automation.toggle_house_mode
          - automation.activity__normal
          - automation.alarm_triggered_notification
          - automation.crypto_price_alerts_bitcoin
          - automation.netflix__pause
        show_header_toggle: true
        title: Automations
        type: entities
      - entities:
          - binary_sensor.door_window_sensor_158d00010673c9
          - sensor.humidity_158d00011003cd
          - light.gateway_light_f0b429cbf3e0
          - sensor.temperature_158d000159f9f2
          - sensor.temperature_158d00011003cd
          - sensor.humidity_158d000159f9f2
          - binary_sensor.motion_sensor_158d00012dae15
          - binary_sensor.motion_sensor_158d0001535b7c
          - binary_sensor.switch_158d00013f9a76
        show_header_toggle: true
        title: Sensors
        type: entities
      - entities:
          - device_tracker.pixel_xl
        show_header_toggle: true
        title: People
        type: entities
      - entities:
          - script.clean_vacuum
          - script.home_vacuum
          - script.max_vacuum
          - script.left_vacuum
          - script.right_vacuum
          - script.forward_vacuum
        show_header_toggle: false
        title: Remotes
        type: entities
      - entity: alarm_control_panel.ha_alarm
        type: alarm-panel
    title: Other
